This notebook is for generating a list of all the filepaths on the EBI cluster for WHO VCFs we want.

In [1]:
import pandas as pd
from pathlib import Path
from collections import defaultdict

In [2]:
ebi_df = pd.read_csv("ena_tb_samples_clockwork_output.csv")

In [3]:
ebi_df

,#Sample.sample_id,Isolate.isolate_id,Seqrep.ena_run_accession,Isolate.ena_experiment_accession,Sample.ena_sample_accession,Sample.ena_study_accession,Pipeline_output
0,1,1,DRR014508,None,SAMD00016703,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...
1,2,2,DRR019444,None,SAMD00017693,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...
2,3,3,DRR019443,None,SAMD00017694,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...
3,4,4,DRR019435,None,SAMD00017695,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...
4,5,5,DRR019436,None,SAMD00017696,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...
...,...,...,...,...,...,...,...
52606,41720,41720,ERR025843,None,SAMEA961586,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...
52607,41721,41721,ERR025844,None,SAMEA961585,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...
52608,41722,41722,ERR025846,None,SAMEA961579,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...
52609,41723,41723,ERR025847,None,SAMEA961640,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...
52610,41724,41724,ERR025848,None,SAMEA961641,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...

In [4]:
who_df = pd.read_csv("../who-samplesheet-filled.csv")

/usr/local/Caskroom/miniconda/base/envs/who-correspondence/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3398: DtypeWarning: Columns (1,3,7,9,10,11,16) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [5]:
who_df

,bioproject,study,biosample,sample,experiment,run,amikacin,bedaquiline,capreomycin,clofazimine,...,ethionamide,ethambutol,isoniazid,kanamycin,levofloxacin,linezolid,moxifloxacin,pyrazinamide,rifampicin,streptomycin
0,PRJEB26001,NaN,NaN,ERS2401626,ERX2536164,ERR2516949,S,NaN,S,NaN,...,NaN,NaN,R,R,S,NaN,S,NaN,R,NaN
1,PRJEB26001,NaN,NaN,ERS2401620,ERX2536158,ERR2516943,S,NaN,S,NaN,...,NaN,R,R,R,R,NaN,R,NaN,R,NaN
2,PRJEB26001,NaN,NaN,ERS2401687,ERX2536225,ERR2517010,S,NaN,S,NaN,...,NaN,NaN,R,S,R,NaN,R,NaN,R,NaN
3,PRJEB26001,NaN,NaN,ERS2401501,ERX2536039,ERR2516824,S,NaN,S,NaN,...,NaN,R,R,S,R,NaN,R,NaN,R,NaN
4,PRJEB26001,NaN,NaN,ERS2401518,ERX2536056,ERR2516841,S,NaN,S,NaN,...,NaN,R,R,S,R,NaN,R,NaN,R,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35956,PRJNA428596,NaN,SAMN08892584,NaN,SRX3906430,SRR6964629,NaN,NaN,S,NaN,...,NaN,S,S,S,S,NaN,S,NaN,S,S
35957,PRJNA428596,NaN,SAMN08892585,NaN,SRX3906429,SRR6964630,NaN,NaN,R,NaN,...,NaN,R,R,R,S,NaN,S,NaN,R,R
35958,PRJNA428596,NaN,SAMN08892586,NaN,SRX3906432,SRR6964627,NaN,NaN,R,NaN,...,NaN,S,S,R,R,NaN,S,NaN,S,S
35959,PRJNA428596,NaN,SAMN08892587,NaN,SRX3906431,SRR6964628,NaN,NaN,S,NaN,...,NaN,S,S,S,S,NaN,S,NaN,S,R
35960,PRJNA428596,NaN,SAMN08892588,NaN,SRX3906433,SRR6964626,NaN,NaN,S,NaN,...,NaN,S,R,S,S,NaN,S,NaN,R,S

In [6]:
who_runs = set(who_df["run"])
len(who_runs)
who_samples = set(who_df["biosample"]).union(set(who_df["sample"]))

In [7]:
ebi_df_subset = ebi_df.query("`Seqrep.ena_run_accession` in @who_runs")

In [8]:
len(ebi_df_subset)

9643

In [9]:
set(ebi_df["Isolate.ena_experiment_accession"])

{'None'}

In [10]:
len(set(ebi_df["Seqrep.ena_run_accession"]))

52611

In [11]:
dir2vcf = defaultdict(list)
with open("ena_minos.fofn") as fp:
    for line in map(str.strip, fp):
        p = Path(line)
        assert p.parts[14] == "Pipelines", line
        d = Path(p.parts[0]).joinpath(*p.parts[1:14])
        if "minos" not in line:
            continue
        dir2vcf[d].append(Path(p.parts[14]).joinpath(*p.parts[15:]))

In [12]:
len(dir2vcf)

41523

In [13]:
minos_vcfs = []
for _, row in ebi_df_subset.iterrows():
    pipeline = Path(row["Pipeline_output"])
    vcfs = dir2vcf.get(pipeline)
    if not vcfs:
        minos_vcfs.append(None)
        continue
    
    if len(vcfs) == 1:
        minos_vcfs.append(vcfs[0])
        continue
        
    max_isolate = ""
    isolate_num = 0
    for v in vcfs:
        iso = v.parts[1]
        if "_" in iso:
            max_isolate = iso
            break
        else:
            if int(iso) > isolate_num:
                max_isolate = iso
                isolate_num = int(iso)
    
    max_min_ver = 0
    latest_vcf = None
    for v in vcfs:
        iso = v.parts[1]
        if iso != max_isolate:
            continue
        minor_ver = int(v.parts[3].split(".")[1])
        if minor_ver > max_min_ver:
            latest_vcf = v
    
    minos_vcfs.append(latest_vcf)

In [14]:
ebi_df_subset["vcf"] = [str(p) for p in minos_vcfs]

/var/folders/0g/3ywwrf6j2vjbp0r780dskt980000gn/T/ipykernel_14777/1169827920.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ebi_df_subset["vcf"] = [str(p) for p in minos_vcfs]

In [93]:
# ebi_df_subset.to_csv("ena_tb_samples_clockwork_output.subset.csv", index=False)

In [94]:
# with open("to_rsync.fofn", "w") as fp:
#     for _, row in ebi_df_subset.iterrows():
#         p = Path(row["Pipeline_output"]) / row["vcf"]
#         print(str(p), file=fp)

In [15]:
ebi_df_subset

,#Sample.sample_id,Isolate.isolate_id,Seqrep.ena_run_accession,Isolate.ena_experiment_accession,Sample.ena_sample_accession,Sample.ena_study_accession,Pipeline_output,vcf
224,225,225,ERR067576,None,SAMEA1015921,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...,Pipelines/1/variant_call/0.8.3.ref.3/minos/fin...
225,226,226,ERR067718,None,SAMEA1015922,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...,Pipelines/1/variant_call/0.8.3.ref.3/minos/fin...
226,227,227,ERR067740,None,SAMEA1015923,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...,Pipelines/1/variant_call/0.7.3.ref.3/minos/fin...
229,230,230,ERR067613,None,SAMEA1015929,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...,Pipelines/1/variant_call/0.8.3.ref.3/minos/fin...
230,231,231,ERR067577,None,SAMEA1015931,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...,Pipelines/1/variant_call/0.7.3.ref.3/minos/fin...
...,...,...,...,...,...,...,...,...
52606,41720,41720,ERR025843,None,SAMEA961586,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...,Pipelines/1/variant_call/0.8.3.ref.3/minos/fin...
52607,41721,41721,ERR025844,None,SAMEA961585,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...,Pipelines/1/variant_call/0.8.3.ref.3/minos/fin...
52608,41722,41722,ERR025846,None,SAMEA961579,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...,Pipelines/1/variant_call/0.8.3.ref.3/minos/fin...
52609,41723,41723,ERR025847,None,SAMEA961640,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...,Pipelines/1/variant_call/0.8.3.ref.3/minos/fin...
52610,41724,41724,ERR025848,None,SAMEA961641,None,/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockw...,Pipelines/1/variant_call/0.8.3.ref.3/minos/fin...

In [17]:
who_df.set_index("run", inplace=True, verify_integrity=True)

In [18]:
ebi_df_subset.set_index("Seqrep.ena_run_accession", inplace=True, verify_integrity=True)

In [43]:
df = ebi_df_subset.join(who_df, how='inner')

In [44]:
df.drop(columns=["Isolate.ena_experiment_accession", "Sample.ena_sample_accession", "Sample.ena_study_accession"], inplace=True)
df.rename(columns={"#Sample.sample_id": "sample_id", "Isolate.isolate_id": "isolate_id"}, inplace=True)

In [45]:
df.iloc[0]["Pipeline_output"]

'/nfs/research/zi/jknaggs/tb/cryptic_ena/Clockwork_ena_tb/Pipeline_root/00/00/02/25/225'

In [46]:
df.iloc[0]["vcf"]

'Pipelines/1/variant_call/0.8.3.ref.3/minos/final.vcf'

In [47]:
vcfs = []
for _, row in df.iterrows():
    root = Path(row["Pipeline_output"])
    v = Path(row["vcf"])
    p = root / v
    assert p.parts[8] == "Pipeline_root"
    vcfs.append(Path(p.parts[8]).joinpath(*p.parts[9:]))

In [48]:
vcfs[0]

PosixPath('Pipeline_root/00/00/02/25/225/Pipelines/1/variant_call/0.8.3.ref.3/minos/final.vcf')

In [49]:
df["vcf"] = vcfs

In [50]:
df.drop(columns=["Pipeline_output"], inplace=True)

In [57]:
df = df.reset_index().rename(columns={"index": "run"})

In [59]:
df.to_csv("who-vcfs.csv", index=False)